### ISSUE TITLE
The diagram and text describing the pinout conflict each other

### ISSUE THREAD

**Issue by mac84tv** [trekawek/mac-plus-ps2#4]
I built this project last night and realized that in the "Connecting to Macintosh Plus" text area on this page shows a list of pinouts (for the phone connector side) that are reversed and do not match those in the visual diagram. For example, it says pin 1 is VCC -> Vin, where it should say pin 1 is GND -> GND as shown in the visual diagram.

This is confusing because I was unsure which example to follow and tried connecting my Arduino both ways. Please correct the text to resolve any potential confusion.

For pure newbies, like myself, it may be helpful to mention that the PS/2 connector shown is from the perspective of using a female socket and that pin 1 of the phone jack is on the left (when the wire side is facing toward you).

Thank you for sharing such a wonderful project!

**Comment by trekawek** [comment]
Hi @mac84tv!
Thanks! Honestly, getting these diagrams right is the most difficult part of the project. This is another iteration and it still wasn't right/clear. Hopefully it'll be better since c32ef172d6570f611adf270ec51a6aec57859c66 and 417ad73bb89ec6a96e4970e4a3d8206232acf18d.

Thanks for the suggestions, have fun with your Mac Plus!

Regards,
Tomek
